// <auto-generated />
using System;
using ITHS_DB_Lab4.DataCon;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITHS_DB_Lab4.Migrations
{
    [DbContext(typeof(LabbContext))]
    [Migration("20200131093534_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ITHS_DB_Lab4.Models.Användare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Namn");

                    b.HasKey("ID");

                    b.ToTable("AnvändareT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.TräningsPass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnvändareID");

                    b.Property<string>("Beskrivning");

                    b.Property<string>("Passnamn");

                    b.Property<string>("Tid");

                    b.Property<string>("Typ");

                    b.HasKey("ID");

                    b.HasIndex("AnvändareID");

                    b.ToTable("TräningspassT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.TräningsUtrustning", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TräningsPassID");

                    b.Property<int?>("UtrustningID");

                    b.HasKey("ID");

                    b.HasIndex("TräningsPassID");

                    b.HasIndex("UtrustningID");

                    b.ToTable("TräningsUtrustningT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.Utrust", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Utrustning");

                    b.HasKey("ID");

                    b.ToTable("UtrustT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.ÖvningDetalj", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JobbighetsNivå");

                    b.Property<int?>("TräningsPassID");

                    b.Property<int?>("ÖvningarID");

                    b.HasKey("ID");

                    b.HasIndex("TräningsPassID");

                    b.HasIndex("ÖvningarID");

                    b.ToTable("ÖvningDetalj");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.Övningar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Repetitioner");

                    b.Property<int>("Sets");

                    b.Property<string>("Övningensnamn");

                    b.HasKey("ID");

                    b.ToTable("ÖvningarT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.TräningsPass", b =>
                {
                    b.HasOne("ITHS_DB_Lab4.Models.Användare", "Användare")
                        .WithMany("TräningsPass")
                        .HasForeignKey("AnvändareID");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.TräningsUtrustning", b =>
                {
                    b.HasOne("ITHS_DB_Lab4.Models.TräningsPass", "TräningsPass")
                        .WithMany("TräningsUtrustning")
                        .HasForeignKey("TräningsPassID");

                    b.HasOne("ITHS_DB_Lab4.Models.Utrust", "Utrustning")
                        .WithMany("TräningsUtrustning")
                        .HasForeignKey("UtrustningID");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.ÖvningDetalj", b =>
                {
                    b.HasOne("ITHS_DB_Lab4.Models.TräningsPass", "TräningsPass")
                        .WithMany("ÖvningDetalj")
                        .HasForeignKey("TräningsPassID");

                    b.HasOne("ITHS_DB_Lab4.Models.Övningar", "Övningar")
                        .WithMany("ÖvningDetalj")
                        .HasForeignKey("ÖvningarID");
                });
#pragma warning restore 612, 618
        }
    }
}
