// <auto-generated />
using System;
using ITHS_DB_Lab4.DataCon;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITHS_DB_Lab4.Migrations
{
    [DbContext(typeof(LabbContext))]
    [Migration("20191212152832_Changes2.0")]
    partial class Changes20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ITHS_DB_Lab4.Models.Användare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Email");

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("ID");

                    b.ToTable("AnvändareT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.FullständigtPass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnvändareID");

                    b.Property<int?>("JobbighetsnivåID")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(5);

                    b.Property<int?>("TräningsPassID");

                    b.Property<int?>("UtrustningID");

                    b.Property<int?>("ÖvningarID");

                    b.HasKey("ID");

                    b.HasIndex("AnvändareID");

                    b.HasIndex("JobbighetsnivåID");

                    b.HasIndex("TräningsPassID");

                    b.HasIndex("UtrustningID");

                    b.HasIndex("ÖvningarID");

                    b.ToTable("FullständigtPassT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.Jobbinivå", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("JobbighetsNivå");

                    b.HasKey("ID");

                    b.ToTable("JobbinivåT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.TräningsPass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Beskrivning");

                    b.Property<string>("Passnamn")
                        .IsRequired();

                    b.Property<string>("Tid");

                    b.Property<string>("Typ");

                    b.HasKey("ID");

                    b.ToTable("TräningspassT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.Utrust", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Utrustning")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("UtrustT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.Övningar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Repetitioner");

                    b.Property<int>("Sets");

                    b.Property<string>("Övningensnamn")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("ÖvningarT");
                });

            modelBuilder.Entity("ITHS_DB_Lab4.Models.FullständigtPass", b =>
                {
                    b.HasOne("ITHS_DB_Lab4.Models.Användare", "Användare")
                        .WithMany()
                        .HasForeignKey("AnvändareID");

                    b.HasOne("ITHS_DB_Lab4.Models.Jobbinivå", "Jobbighetsnivå")
                        .WithMany()
                        .HasForeignKey("JobbighetsnivåID");

                    b.HasOne("ITHS_DB_Lab4.Models.TräningsPass", "TräningsPass")
                        .WithMany()
                        .HasForeignKey("TräningsPassID");

                    b.HasOne("ITHS_DB_Lab4.Models.Utrust", "Utrustning")
                        .WithMany()
                        .HasForeignKey("UtrustningID");

                    b.HasOne("ITHS_DB_Lab4.Models.Övningar", "Övningar")
                        .WithMany()
                        .HasForeignKey("ÖvningarID");
                });
#pragma warning restore 612, 618
        }
    }
}
